name: Run Tests
on:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11.1"
        cache: "pipenv"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --ignore-pipfile --dev
    - name: Run tests
      run: |
        pipenv run pytest
